### ISSUE TITLE
WIKI: wrong version in installation instruction

### ISSUE THREAD

**Issue by ekitru** [libgdx/libgdx-maven-archetype#11]
Hi,

Can you update please instruction for installing from Maven, currently version 0.9.9 not available on server, instead 1.0-SNAPSHOT available

**Comment by nigue** [comment]
Like said ekitru

 libgdx-maven-archetype needs 2 urgent changes

1) pom.xml; line 6

```
<version>1.0-SNAPSHOT</version>
```

to

```
<version>0.9.9</version>
```

2) in architype:generate command line

% mvn archetype:generate \
    -DarchetypeRepository=local \
    -DarchetypeRepository=$HOME/.m2/repository \
    -DarchetypeGroupId=com.badlogic.gdx \
    -DarchetypeArtifactId=gdx-archetype \
    -DarchetypeVersion=0.9.9-SNAPSHOT

to

% mvn archetype:generate \
    -DarchetypeRepository=local \
    -DarchetypeRepository=$HOME/.m2/repository \
    -DarchetypeGroupId=com.badlogic.gdx \
    -DarchetypeArtifactId=gdx-archetype \
    -DarchetypeVersion=1.0-SNAPSHOT

**Comment by targeter21** [comment]
I also ran into this issue. It's a very simple change that can fix what otherwise might potentially screw up new users.

https://github.com/libgdx/libgdx/wiki/Maven-integration

EDIT: I modified the wiki to show the correct version.

**Comment by davidrehakcz** [comment]
Hi,
im new to libgdx and i do confirm that it was quite annoying to find out myself the problem of libgdx version within the Wiki command. Furthermore i had to change the android maven version (from 3.6.6. to 3.8.1) as well to actually build the project. I would really suggest to review the archetype for newcomers. 
One more thing, is there a way to target android API >15 ? As actual version within pom.xml points only to API 15.

**Comment by targeter21** [comment]
home-bot, you can make the change yourself and create a pull request for it :). (I am not a member of the project)

**Comment by davidrehakcz** [comment]
Well, i have just reviewed other PR, and it seems theres already one for the android maven version. For the command, its just matter of the Wiki within the official libgdx webpages, as in github, its actually correct :-) I, finally, go now  code something using libgdx :-)

**Comment by targeter21** [comment]
This issue can be closed now that the docs are updated.

**Comment by MobiDevelop** [comment]
Merged #15 to update the Android maven version.
