### ISSUE TITLE
Libgdx 0.9.8 archetype in repository

### ISSUE THREAD

**Issue by tomcashman** [libgdx/libgdx-maven-archetype#2]
Would it be possible to push a tagged version of 0.9.8 and its archetype to your repository? If I'm building/releasing a game using Maven I'd like to be able to release using a tagged version as to avoid any possible bugs introduced in nightly builds.

**Comment by badlogic** [comment]
we plan on releasing 0.9.9 to maven central properly. retroactively publishing 0.9.8 is a bit complex, mostly because of natibes.
