### ISSUE TITLE
Maven can't resolve gdx depency.

### ISSUE THREAD

**Issue by zergood** [libgdx/libgdx-maven-archetype#21]
Then I have generated maven project according to documentation. In parent pom file gdx.version is 0.9.9-SNAPSHOT. Maven can't resolve it. And I think it is an old version and needs to be changed.

**Comment by johnnyapol** [comment]
Should be resolved by 7c4a02b4b2f39e5d501ea8e4175072130129e213 which @MobiDevelop committed earlier today. Try the latest changes please and reopen if you have anymore issues.
