### ISSUE TITLE
mvn -Pandroid package fail : NoClassDefFoundError: Lorg/sonatype/aether/RepositorySystem

### ISSUE THREAD

**Issue by jagt** [libgdx/libgdx-maven-archetype#7]
Hi. I'm trying to follow the wiki to setup maven project and import it to Intellj.
The desktop package goal works fine. But the android one is not working.
Here's the log

https://gist.github.com/jagt/6570775

Another issue is that when I'm trying to import it into IntelliJ the desktop profile works fine. But when I running the package goal of android profile, it complains that can't find the core module:

```
[ERROR] Failed to execute goal on project plasma-android: Could not resolve dependencies for project com.pre_sence.plasma:plasma-android:apk:0.0-DEV: Failure to find com.pre_sence.plasma:plasma-core:jar:0.0-DEV in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of gdx-nightlies has elapsed or updates are forced -> [Help 1]
```

**Comment by badlogic** [comment]
Based on your Gist, it seems the android maven plugin is exploding, so 
it's not necessarily an archetype issue. You could check if there's a 
newer Android maven plugin version, and manually update the Android 
project's pom.

As for IntelliJ, I'm not exactly sure how that interplays with Android 
and Maven.

**Comment by jagt** [comment]
Thanks for the quick reply. I'll try updating android maven plugin later. In fact all I'm trying to do is to setup a project in IntelliJ, since the setup ui would generate eclipse projects, which used some features that IntelliJ can't import properly. And setting up manually seems to quite tedious and I'm not sure I can properly setup the gwt and ios one. Any idea on which is the best way to create a IntelliJ project?

**Comment by badlogic** [comment]
There's a guide for manually setting up desktop and Android projects in
Intellij on the wiki. GWT can't be supported in Intellij i'm afraid.
There's also currently no Intellij support for RoboVM. We are working on a
new tool that should fix those things. No ETA though.

**Comment by jagt** [comment]
Cool! You can close this issue and I'll figure the maven thing out myself :)
